apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: role-{{ .Release.Name }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "namespaces", "deployments",]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]