apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-{{ .Release.Name }}
  namespace: api
subjects:
- kind: Group
  name: system:serviceaccounts:api
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io