apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbsecret.name }}-{{ .Release.Name}}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_HOST: {{ .Values.dbsecret.rdsurl | b64enc }}
  DB_USER: cG9zdGdyZXM=
  DB_PASS: cm9vdHJvb3Q=
  DB_PORT: NTQzMg==
  DB_NAME: cmVjaXBl
  BUCKET_NAME: {{ .Values.bucketname | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKey | b64enc }}
  SECRET_ACCESS_KEY_ID: {{ .Values.awsSecretKey | b64enc }}
